builders:
  feature_manager_generator:
    target: ":featureManagerGenerator"
    import: "package:feature_manager_generator/feature_manager_generator.dart"
    builder_factories: ["featureManagerGenerator"]
    build_extensions: { ".dart": [".fm.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
