name: feature_manager_generator
description: Feature manager generator for developer preferences and experiments
publish_to: none
# repository: https://github.com/theRealGetman/feature-manager/tree/master/feature_manager_generator
# issue_tracker: https://github.com/theRealGetman/feature-manager/issues
version: 1.0.0

environment:
  sdk: ">=3.2.4 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^6.7.0
  build: ^2.4.1
  source_gen: ^1.5.0
  feature_manager:
    path: ../feature_manager # TODO(hrubalski): replace it with just a version
    # git:
    #   url: git@github.com:hrubalski/feature-manager.git
    #   ref: feat-feature-manager-generator
    #   path: feature_manager

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
