name: feature_manager_generator
description: Feature manager generator for developer preferences and experiments
version: 1.0.0
repository: https://github.com/theRealGetman/feature-manager
issue_tracker: https://github.com/theRealGetman/feature-manager/issues

environment:
  sdk: ">=3.2.4 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
