name: feature_manager_generator
description: Feature manager generator for developer preferences and experiments
repository: https://github.com/theRealGetman/feature-manager/tree/master/generator
issue_tracker: https://github.com/theRealGetman/feature-manager/issues

version: 3.0.5

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  analyzer: ^6.7.0
  build: ^2.4.1
  source_gen: ^1.5.0
  feature_manager: ^3.0.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
