# Analyze before publish: flutter pub publish --dry-run
# Publish: flutter pub publish
name: feature_manager
description: Feature manager for developer preferences and experiments
version: 1.1.1
repository: https://github.com/theRealGetman/feature-manager
issue_tracker: https://github.com/theRealGetman/feature-manager/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  bloc_test: ^9.1.1
  mockito: ^5.3.2
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3

# The following section is specific to Flutter.
flutter: