name: feature_manager
description: Feature manager for developer preferences and experiments
version: 1.0.0
repository: https://gitlab.com/playseek/feature-manager
issue_tracker: https://gitlab.com/playseek/feature-manager/-/issues
authors:
  - "Artem Getman (a.e.getman@gmail.com)"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.2.0
  bloc_test: ^8.2.0
  mockito: ^5.0.15
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2

# The following section is specific to Flutter.
flutter: